;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        c-electric-paren
        c-electric-semi&comma
        downcase-region
        emmet-expand-line
        end-of-buffer
        kill-region
        kill-sexp
        paredit-backward-kill-word
        paredit-close-round
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        paredit-open-curly
        paredit-open-round
        paredit-open-square
        paredit-semicolon
        paredit-wrap-round
        upcase-region
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ))
