(add-to-list 'load-path "~/.emacs.d/elpa/auto-complete-20150618.1949/")
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "~/.emacs.d/dict/")
(global-auto-complete-mode t)
(ac-config-default)
(provide 'auto-complete-init)
